import abc
from pydantic import BaseModel, Field
from typing import List, Dict, Any


class Message(BaseModel):
    """
    A schema for messages passed to the LLM client.
    """
    role: str = Field(
        ...,
        example="user",
        description="Role of the message sender (e.g., 'user', 'assistant')."
    )
    content: str = Field(
        ...,
        example="What is the weather today?",
        description="Content of the message."
    )


class LLMClientBase(metaclass=abc.ABCMeta):
    """
    Abstract base class for LLM clients. Defines the standard interface
    for any LLM client implementation (e.g., OpenAI, Azure, etc.).
    """

    @abc.abstractmethod
    def generate_response(self, messages: List[Message]) -> Dict[str, Any]:
        """
        Generates a response from the LLM based on the input messages.
        :param messages: A list of messages following the conversation format.
        :return: The response generated by the LLM.
        """
        raise NotImplementedError


