import openai
from typing import List, Dict, Any
from pydantic import Optional
from src.llm_client.base import LLMClientBase, Message
import json


class OpenAIClient(LLMClientBase):
    """
    An implementation of the LLMClientBase for OpenAI's GPT-based APIs.
    """
    def __init__(self, api_key: str, model: str = "gpt-3.5-turbo"):
        """
        Initializes the OpenAI client with the API key and default model.
        :param api_key: The API key for authenticating with OpenAI.
        :param model: The OpenAI model to use for generating responses.
        """
        self.api_key = api_key
        self.model = model
        openai.api_key = self.api_key

    def generate_response(self, messages: List[Message]) -> Dict[str, Any]:
        """
        Generates a response using the OpenAI API.
        :param messages: A list of messages to pass to the OpenAI API.
        :return: The response generated by OpenAI.
        """
        try:
            formatted_messages = [{"role": msg.role, "content": msg.content} for msg in messages]
            response = openai.ChatCompletion.create(
                model=self.model,
                messages=formatted_messages
            )
            return response
        except Exception as e:
            raise RuntimeError(f"Failed to generate response: {e}")

    @staticmethod
    def validate_message(message: Message) -> bool:
        """
        Validates whether the provided message conforms to the schema.
        :param message: A single message to validate.
        :return: True if valid, False otherwise.
        """
        return bool(message.role and message.content)
    
    def evaluate_relevance(self, title: str, prompt: str = "民生用品的價格變化") -> str:
        """
        使用 LLM 判斷新聞標題與「民生用品的價格變化」的關聯性。
        """
        messages: List[Message] = [
            Message(
                role="system",
                content="你是一個關聯度評估機器人，請評估新聞標題是否與「{prompt}」相關，並給予'high'、'medium'、'low'評價。(僅需回答'high'、'medium'、'low'三個詞之一)"
            ),
            Message(
                role="user",
                content=title
            ),
        ]
        response = self.generate_response(messages)
        return response["choices"][0]["message"]["content"].strip()

    def generate_summary(self, prompt: str) -> dict:
        """
        使用 LLM 生成新聞摘要，提取影響和原因。
        """
        messages: List[Message] = [
            Message(
                role="system",
                content="你是一個新聞摘要生成機器人，請統整新聞中提及的影響及主要原因 (影響、原因各50個字，請以json格式回答 {'影響': '...', '原因': '...'})"
            ),
            Message(
                role="user",
                content=prompt
            ),
        ]
        response = self.generate_response(messages)
        return json.loads(response["choices"][0]["message"]["content"])

    def extract_search_keywords(self, prompt: str) -> Optional[str]:
        """
        使用 OpenAI 提取用戶希望看到的新聞內容中的關鍵字。

        :param prompt: 用戶輸入的一段文字，表示希望看到的新聞內容。
        :return: 提取出的關鍵字（以空格分隔的字符串）。
        """
        messages = [
            Message(
                role="system",
                content="你是一個關鍵字提取機器人，用戶將會輸入一段文字，表示其希望看見的新聞內容，請提取出用戶希望看見的關鍵字，請截取最重要的關鍵字即可，避免出現「新聞」、「資訊」等混淆搜尋引擎的字詞。(僅須回答關鍵字，若有多個關鍵字，請以空格分隔)"
            ),
            Message(role="user", content=prompt),
        ]

        try:
            # 调用 generate_response 方法获取 API 返回结果
            response = self.generate_response(messages)
            keywords = response["choices"][0]["message"]["content"].strip()
            return keywords
        except Exception as e:
            print(f"Error extracting keywords: {e}")
            return None


       
