import openai
from typing import List, Dict, Any, Optional
from src.llm_client.base import LLMClientBase, Message
import json


class OpenAIClient(LLMClientBase):
    """
    An implementation of the LLMClientBase for OpenAI's GPT-based APIs.
    """
    def __init__(self, api_key: str, model: str = "gpt-3.5-turbo"):
        """
        Initializes the OpenAI client with the API key and default model.
        :param api_key: The API key for authenticating with OpenAI.
        :param model: The OpenAI model to use for generating responses.
        """
        self.api_key = api_key
        self.model = model
        openai.api_key = self.api_key
    

    def generate_response(self, messages: List[Message]) -> Dict[str, Any]:
        """
        Generates a response using the OpenAI API.
        :param messages: A list of messages to pass to the OpenAI API.
        :return: The response generated by OpenAI.
        """
        #try:
        formatted_messages = [{"role": msg.role, "content": msg.content} for msg in messages]
        response = openai.ChatCompletion.create(
            model=self.model,
            messages=formatted_messages
        )
        return response
        #except Exception as e:
            #raise RuntimeError(f"Failed to generate response: {e}")
    
    def evaluate_relevance(self, messages: List[Message]) -> str:
        """
        Uses the LLM to evaluate the relevance of a news headline.
        :param messages: A list of messages to pass to the LLM for evaluation.
        :return: The relevance score ('high', 'medium', 'low').
        """
        response = self.generate_response(messages)
        return response["choices"][0]["message"]["content"].strip()
    
    def generate_summary(self, messages: List[Message]) -> dict:
        """
        Uses the LLM to generate a summary, extracting impact and reasons.
        :param messages: A list of messages to pass to the LLM for summary generation.
        :return: A dictionary containing the summary and reasons.
        """
        
        response = self.generate_response(messages)
        return json.loads(response["choices"][0]["message"]["content"])

    def extract_search_keywords(self, messages: List[Message]) -> Optional[str]:
        """
        Uses OpenAI to extract keywords from the user's input.
        :param messages: A list of messages to pass to the LLM for keyword extraction.
        :return: Extracted keywords as a space-separated string.
        """
        # try:
        response = self.generate_response(messages)
        keywords = response["choices"][0]["message"]["content"].strip()
        return keywords
        #except Exception as e:
        #    print(f"Error extracting keywords: {e}")
         #   return None


       
